// cliente-vue/src/components/BarraLateral.vue
<template>
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 200px;">
    <img
    @click="esconder"
        :src="menu"
        :class="barra-escondida"
        class="m-1"
        alt="Logo"
        width="24"
        height="20"
      />
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <RouterLink :to="{name: 'dashboard'}" :class="navSelect" @click="navSelect" value="home" class="nav-link active" aria-current="page">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          Bienvenida
        </font></font></RouterLink>
      </li>
      <li>
        <RouterLink :to="{name: 'dashboard-panel'}" :class="navSelect" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          Panel
        </font></font></RouterLink>
      </li>
      <li>
        <RouterLink :to="{name: 'dashboard-colaboradores'}" :class="navSelect" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          Colaboradores
        </font></font></RouterLink>
      </li>
      <li>
        <RouterLink :to="{name: 'dashboard-proyectos'}" :class="navSelect" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          Proyectos
        </font></font></RouterLink>
      </li>
      <li>
        <RouterLink :to="{name: 'dashboard-clientes'}" :class="navSelect" class="nav-link text-white">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          Clientes
        </font></font></RouterLink>
      </li>
    </ul>
    <hr>
   
  </div>


  
</template>

<script setup>
import { computed, ref } from '@vue/runtime-core'
import menu from '../assets/menu.png'


const navSelect = (e) =>{
  console.log(e.getAttribute('class'));
  console.log(e.target);
  console.log(e.target.value);

}

// const navSelect = computed(() =>{

//     return 'bg-danger'
  
//     // return selectNav.value = 'bg-primary' 
// })

const esconder = () => {
    return ''
}

</script>

<style scoped></style>

// cliente-react/src/components/BarraLateral.jsx
import React from 'react'
import { Link } from 'react-router-dom'

function BarraLateral() {
  return (
    
        <div className="d-flex flex-column flex-shrink-0 p-3 text-bg-dark w-25" >
    <img
        className="m-1"
        alt="Logo"
        width="24"
        height="20"
      />
    <hr/>
    <ul className="nav nav-pills flex-column mb-auto">
      <li className="nav-item">
        <Link to={'/dashboard'} value="home" className="nav-link active" aria-current="page">
        <svg className="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Bienvenido</Link>
      </li>
      <li>
        <Link to={'/dashboard/panel'} className="nav-link text-white">
          <svg className="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>Panel</Link>
      </li>
      <li>
        <Link to={'/dashboard/colaboradores'} className="nav-link text-white">
          <svg className="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>Colaboradores</Link>
      </li>
      <li>
        <Link to={'/dashboard/proyectos'} className="nav-link text-white">
          <svg className="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>Proyectos</Link>
      </li>
      <li>
        <Link to={'/dashboard/clientes'} className="nav-link text-white">
          <svg className="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>Clientes</Link>
      </li>
    </ul>
    <hr/>
   
    </div>
  )
}

export default BarraLateral
