// cliente-vue/src/components/Footer.vue
<template>
  
  <footer class="py-3  bg-dark ">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3 text-white">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-white">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-white">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-white">About</a></li>
    </ul>
    <p class="text-center text-white">© 2022 Company, Inc</p>
  </footer>

</template>

// cliente-react/src/components/Footer.jsx
import React from 'react'

function Footer() {
  return (
    <div>
          <footer className="py-3  bg-dark ">
    <ul className="nav justify-content-center border-bottom pb-3 mb-3 text-white">
      <li className="nav-item"><a href="#" className="nav-link px-2 text-white">Home</a></li>
      <li className="nav-item"><a href="#" className="nav-link px-2 text-white">Features</a></li>
      <li className="nav-item"><a href="#" className="nav-link px-2 text-white">Pricing</a></li>
      <li className="nav-item"><a href="#" className="nav-link px-2 text-white">FAQs</a></li>
      <li className="nav-item"><a href="#" className="nav-link px-2 text-white">About</a></li>
    </ul>
    <p className="text-center text-white">© 2022 Company, Inc</p>
  </footer>

    </div>
  )
}

export default Footer
